In [6]:
import pandas as pd
import os

In [7]:
final_orders = pd.read_csv("/app/data/final_orders.csv")

In [8]:
final_orders.shape

(99441, 31)

In [11]:
final_orders["order_delivered_customer_date"]

0        2017-10-10 21:25:13
1        2018-08-07 15:27:45
2        2018-08-17 18:06:29
3        2017-12-02 00:28:42
4        2018-02-16 18:17:02
                ...
99436    2017-03-17 15:08:01
99437    2018-02-28 17:37:56
99438    2017-09-21 11:24:17
99439    2018-01-25 23:32:54
99440    2018-03-16 13:08:30
Name: order_delivered_customer_date, Length: 99441, dtype: str

In [5]:
labeled_orders = final_orders[
    final_orders["order_delivered_customer_date"].notna()
].copy()

In [12]:
labeled_orders.shape

(96476, 31)

In [13]:
date_columns = [
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

labeled_orders[date_columns] = labeled_orders[date_columns].apply(
    pd.to_datetime
)

In [14]:
labeled_orders[date_columns].dtypes

order_delivered_customer_date    datetime64[us]
order_estimated_delivery_date    datetime64[us]
dtype: object

In [15]:
labeled_orders["is_late"] = (
    labeled_orders["order_delivered_customer_date"]
    > labeled_orders["order_estimated_delivery_date"]
).astype(int)

In [16]:
labeled_orders[
    [
        "order_id",
        "order_delivered_customer_date",
        "order_estimated_delivery_date",
        "is_late"
    ]
].head(10)

,order_id,order_delivered_customer_date,order_estimated_delivery_date,is_late
0,e481f51cbdc54678b7cc49136f2d6af7,2017-10-10 21:25:13,2017-10-18,0
1,53cdb2fc8bc7dce0b6741e2150273451,2018-08-07 15:27:45,2018-08-13,0
2,47770eb9100c2d0c44946d9cf07ec65d,2018-08-17 18:06:29,2018-09-04,0
3,949d5b44dbf5de918fe9c16f97b45f8a,2017-12-02 00:28:42,2017-12-15,0
4,ad21c59c0840e6cb83a9ceb5573f8159,2018-02-16 18:17:02,2018-02-26,0
5,a4591c265e18cb1dcee52889e2d8acc3,2017-07-26 10:57:55,2017-08-01,0
7,6514b8ad8028c9f2cc2374ded245783f,2017-05-26 12:55:51,2017-06-07,0
8,76c6e866289321a7c93b82b54852dc33,2017-02-02 14:08:10,2017-03-06,0
9,e69bfb5eb88e0ed6a785585b27e16dbf,2017-08-16 17:14:30,2017-08-23,0
10,e6ce16cb79ec1d90b1da9085a6118aeb,2017-05-29 11:18:31,2017-06-07,0

In [17]:
labeled_orders[
    labeled_orders["is_late"] == 1
][
    [
        "order_id",
        "order_delivered_customer_date",
        "order_estimated_delivery_date",
        "is_late"
    ]
].head(10)

,order_id,order_delivered_customer_date,order_estimated_delivery_date,is_late
20,203096f03d82e0dffbc41ebc2e2bcfb7,2017-10-09 22:23:46,2017-09-28,1
25,fbf9ac61453ac646ce8ad9783d7d0af6,2018-03-21 22:03:54,2018-03-12,1
35,8563039e855156e48fccee4d611a3196,2018-03-20 00:59:25,2018-03-20,1
41,6ea2f835b4556291ffdc53fa0b3b95e8,2017-12-28 18:59:23,2017-12-21,1
57,66e4624ae69e7dc89bd50222b59f581f,2018-04-03 13:28:46,2018-04-02,1
58,a685d016c8a26f71a0bb67821070e398,2017-04-06 13:37:16,2017-03-30,1
97,6a0a8bfbbe700284feb0845d95e0867f,2017-12-28 19:43:00,2017-12-11,1
102,a5474c0071dd5d1074e12d417078bbd0,2018-08-03 19:28:47,2018-08-02,1
110,9d531c565e28c3e0d756192f84d8731f,2018-01-23 21:38:52,2017-12-22,1
115,8fc207e94fa91a7649c5a5dab690272a,2018-01-20 13:42:22,2017-12-19,1

In [18]:
labeled_orders["is_late"].value_counts()

is_late
0    88649
1     7827
Name: count, dtype: int64

In [19]:
labeled_orders["is_late"].value_counts(normalize=True) * 100

is_late
0    91.887101
1     8.112899
Name: proportion, dtype: float64

In [20]:
labeled_orders["is_late"].isna().sum()

np.int64(0)

In [21]:
print("Rows:", len(labeled_orders))
print("Unique orders:", labeled_orders["order_id"].nunique())
print(
    "1 row = 1 order:",
    len(labeled_orders) == labeled_orders["order_id"].nunique()
)

Rows: 96476
Unique orders: 96476
1 row = 1 order: True

In [22]:
labeled_orders.to_csv(
    "/app/data/labeled_orders.csv",
    index=False
)

In [23]:
os.path.exists("/app/data/labeled_orders.csv")

True